"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.container = void 0;
var inversify_1 = require("inversify");
var inversify_types_1 = require("../types/inversify.types");
var transaction_controller_1 = require("../../application/controllers/transaction-controller");
var transaction_application_service_1 = require("../../domain/domain-application-service/transaction-application-service");
var transaction_repository_1 = require("../../data-access/repository/transaction-repository");
var container = new inversify_1.Container();
exports.container = container;
container.bind(inversify_types_1.TYPES.TransactionController).to(transaction_controller_1.TransactionController);
container.bind(inversify_types_1.TYPES.TransactionApplicationService).to(transaction_application_service_1.TransactionApplicationService);
container.bind(inversify_types_1.TYPES.TransactionRepository).to(transaction_repository_1.TransactionRepository);
